AWSTemplateFormatVersion: '2010-09-09'
Description: log-tracker-backend
Transform:
- AWS::Serverless-2016-10-31
Globals:
  Function:
    Layers:
    - Ref: RuntimeDependenciesLayer
    Environment:
      Variables:
        SAMPLE_BUCKET:
          Ref: LogDataBucket
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 100
Resources:
  getLogsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
      SamResourceId: getLogsFunction
    Properties:
      Handler: dist/handlers/get-logs.getLogsHandler
      Policies:
      - S3ReadPolicy:
          BucketName:
            Ref: LogDataBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /logs/{group}
            Method: GET
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-bquygjrbevos/e6ba93f38d2fc2c4e452e4e539b3148d
  postLogsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
      SamResourceId: postLogsFunction
    Properties:
      Handler: dist/handlers/post-logs.postLogsHandler
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: LogDataBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /logs
            Method: POST
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-bquygjrbevos/e6ba93f38d2fc2c4e452e4e539b3148d
  LogDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-log-data-wealthos
      AccessControl: Private
    Metadata:
      SamResourceId: LogDataBucket
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
      SamResourceId: RuntimeDependenciesLayer
    Properties:
      LayerName: log-tracker-backend-dependencies
      Description: Runtime dependencies for Lambdas
      ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-bquygjrbevos/e6ba93f38d2fc2c4e452e4e539b3148d
      CompatibleRuntimes:
      - nodejs18.x
      RetentionPolicy: Retain
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
