version = 0.1
[default.deploy.parameters]
stack_name = "log-tracker-backend"
s3_bucket = "s3-log-data-wealthos"
s3_prefix = "log-tracker-backend"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
